spring:
  application:
    name: taco-cloud
  datasource:
    generate-unique-name: false
    name: tacocloud
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: qwerty
  sql:
    init:
      mode: always
#  jpa:
#    hibernate:
#      ddl-auto: none
